version: "3.9"
   
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - .:/code
    - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: gunicorn elderlyhome.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"