# Generated by Django 3.2 on 2021-04-22 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='home',
            name='lt_sym_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='pttn_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='sido_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='sigungu_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
