# Generated by Django 3.2 on 2021-04-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20210422_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungu_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='sido_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.sido'),
        ),
        migrations.AlterField(
            model_name='home',
            name='sigungu_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.sigungu'),
        ),
    ]
