# Generated by Django 3.2 on 2021-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20210422_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='sido',
            name='sido_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sigungu',
            name='sigungu_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
