# Generated by Django 3.2 on 2021-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20210422_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigungu',
            name='sido_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homes.sido'),
            preserve_default=False,
        ),
    ]
