# Generated by Django 3.2 on 2021-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_sigungu_sido_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['created_date'], 'verbose_name': '양로원 정보', 'verbose_name_plural': '양로원 정보'},
        ),
        migrations.AlterModelOptions(
            name='sido',
            options={'ordering': ['sido_code'], 'verbose_name': '시도 코드', 'verbose_name_plural': '시도 코드'},
        ),
        migrations.AlterModelOptions(
            name='sigungu',
            options={'ordering': ['sigungu_code'], 'verbose_name': '시군구 코드', 'verbose_name_plural': '시군구 코드'},
        ),
        migrations.AddField(
            model_name='home',
            name='is_address_find_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='is_latlng_find_done',
            field=models.BooleanField(default=False),
        ),
    ]
