# Generated by Django 3.2 on 2021-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20210423_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_detail_find_done',
            field=models.BooleanField(default=False),
        ),
    ]
